#定义持续集成(CI)阶段
stages:
#  - build
  - docker-build
  - test
  - test2
  - docker-run
  - test
#定义job:
#job-bbs
bbs:
  stage: test
  script:
    - echo "bbs.beging test..."
    - mkdir -p /tmp/gitlabttt/
    - echo "doing test" >> /tmp/gitlabttt/t1.txt
    - echo "bbs.stop test..."
#  You can setup jobs to only use Runners with specific tags. Separate tags with commas.
#  tags:
# TODO 可以成功,不过由于这个tags注册的runner是个docker的.就用docker安装了.
#而这个我还不是很了解.先跳过.
#    - pytesttag


#job-bbsb
bbsb:
#  stage: build
#  使用未声明的阶段build,gitlab会报错(yaml invalid ).
  stage: test
  script:
    - echo "bbsb.beging build..."
    - mkdir -p /tmp/gitlabttt/
    - echo "doing build" >> /tmp/gitlabttt/t2.txt
    - echo "bbsb.stop build..."

myjob2:
  stage: test2
  script:
    - echo "iam test 2..."
    - echo "iam test 2..."
    - echo "iam test 我是新代码..."
    - pwd
    - whoami
    - env > /tmp/gitlabttt/env.txt
    - git status
    - allcolor.sh
  when: manual

builddocker:
  stage: docker-build
  script:
    - echo "doing build docker image ${CI_PROJECT_NAME}"
    - ./build.sh build
    - echo "finish build docker image."

rundocker:
  stage: docker-run
  script:
    - echo "doing run docker container ${CI_PROJECT_NAME}"
    - ./build.sh run
    - echo "finish run docker container."
